GET http://localhost:3001/todos

###


POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order pizza"
}


###

DELETE http://localhost:3001/todo/delete/636ad071c418fdf7180e91f9


###

PUT http://localhost:3001/todo/complete/636ad070c418fdf7180e91f7