GET http://localhost:3001/todos

###


POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Roast Gaby's outfit"
}

###

DELETE http://localhost:3001/todo/delete/636b34227510cd93ada8c7b9


###

PUT http://localhost:3001/todo/complete/636ad06ec418fdf7180e91f5